### ISSUE TITLE
Please fix deprecated (as of sbt 1.5.0) 'in' syntax

### ISSUE THREAD

**Issue by tuxji** [alejandrohdezma/sbt-codecov#114]
Since sbt 1.5.0, Apache Daffodil's CI workflow prints a warning.  I can't find "coverageEnabled" anywhere in the daffodil repository but I do find it in the sbt-codecov repository so that's why I'm reporting the issue here.

```log
[info] Reapplying settings...
[info] set current project to daffodil (in build file:/home/runner/work/daffodil/daffodil/)
<set>:1: warning: method in in trait ScopingSetting is deprecated (since 1.5.0): `in` is deprecated; migrate to slash syntax - https://www.scala-sbt.org/1.x/docs/Migrating-from-sbt-013x.html#slash
coverageEnabled in ThisBuild := true
                ^
[info] Defining ThisBuild / coverageEnabled
[info] The new value will be used by Compile / compile / scalacOptions, daffodil-cli / Compile / compile / scalacOptions and 35 others.
[info] 	Run `last` for details.
[info] Reapplying settings...
```

Here's a search which will pinpoint 3 places to be changed but it wasn't an exhaustive search; there may be other places where the deprecated 'in' syntax is used too.

<https://github.com/alejandrohdezma/sbt-codecov/search?q=coverageEnabled+in+ThisBuild+%3A%3D+true>

**Comment by alejandrohdezma** [comment]
Hi! Thank you very much for reminding me of this, I've been updating my repos to the new syntax and haven't reach this one yet.

Regarding the issue [I have already send a PR](https://github.com/alejandrohdezma/sbt-codecov/pull/115) fixing the code provoking warnings and will publish a new version once Bintray is back up and test pass. However I don't think that'll fix your issue since it seems [you are using plain `sbt-scoverage`](https://github.com/apache/daffodil/blob/04beffc77afb93e51098c78eaf33ca0c38956e5b/project/plugins.sbt#L22) in your build instead of this plugin. In that case the code provoking those warnings will be [this one](https://github.com/scoverage/sbt-scoverage/blob/aaff04cc6e79e48418a22ec21d15e9d8d96c3dde/src/main/scala/scoverage/ScoverageSbtPlugin.scala#L43-L45).

**Comment by tuxji** [comment]
Thank you for pointing me in the correct direction!  I see that someone already created a [pull request](https://github.com/scoverage/sbt-scoverage/pull/322) in the sbt-coverage project with the necessary changes but their CI is broken so it hasn't been merged yet (darn it).  Meanwhile, thanks again for updating sbt-codecov to the new syntax :).
